var PUZZLE_ROWS = [];
PUZZLE_ROWS[0] = "QWERTYIOPU";
PUZZLE_ROWS[1] = "DUCKINGHEN";
PUZZLE_ROWS[2] = "OPULKITEFA";
PUZZLE_ROWS[3] = "GATELFGLAU";
PUZZLE_ROWS[4] = "RNCDIHOLNG";
PUZZLE_ROWS[5] = "OTJYOZWOMH";
PUZZLE_ROWS[6] = "HKHINHLKOT";
PUZZLE_ROWS[7] = "ALMYELLOWY";
PUZZLE_ROWS[8] = "NNQPDEFSTI";
PUZZLE_ROWS[9] = "BSLJDHUOSK";

module.exports = {
	puzzle1: PUZZLE_ROWS
};